Implemented Evo Steel Soul Controller
Talishar/Talishar pull request #635
Opened 2023-09-30 19:45 UTC by KuKetto

2023-09-30 20:26 UTC, OotTheMonk commented on MZLogic.php
For the MZAddZone change, shouldn't you be parsing the parameter out of "last result" instead of parameter? I'm thinking it might be better to rename parameter and lastresult to be like "search" and "destination"

2023-09-30 20:26 UTC, OotTheMonk requested changes
One small comment/suggestion

2023-09-30 20:35 UTC, KuKetto commented on MZLogic.php
hmm good point, i was just thinking on a quick way to do that. however this isn't a good choice

2023-10-01 13:42 UTC, OotTheMonk approved these changes

2023-10-01 13:42 UTC, merged